[project]
name = "nostr-sdk"
version = "0.12.0"
description = "High level Nostr client library."
authors = [
    { name = "Yuki Kishimoto", email = "yukikishimoto@protonmail.com" },
]
maintainers = [
    { name = "Yuki Kishimoto", email = "yukikishimoto@protonmail.com" },
]
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["nostr", "rust-nostr", "sdk"]

[project.urls]
Homepage = "https://rust-nostr.org"
Documentation = "https://rust-nostr.org"
Repository = "https://github.com/rust-nostr/nostr.git"
Issues = "https://github.com/rust-nostr/nostr/issues"
Changelog = "https://rust-nostr.org/changelog"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["nostr_sdk"]

[tool.setuptools.package-dir]
nostr_sdk = "./src/nostr-sdk"

[tool.pytest.ini_options]
pythonpath = ["."]