[workspace]
members = [
    "bindings/nostr-ffi",
    "bindings/nostr-js",
    "bindings/nostr-sdk-ffi",
    "bindings/nostr-sdk-js",
    "bindings/uniffi-bindgen",
    "crates/*",
]
default-members = ["crates/*"]
resolver = "2"

[workspace.package]
homepage = "https://github.com/rust-nostr/nostr"
repository = "https://github.com/rust-nostr/nostr.git"
license = "MIT"
rust-version = "1.64.0"

[workspace.dependencies]
async-trait = "0.1"
nostr = { version = "0.25", path = "./crates/nostr", default-features = false }
once_cell = "1.18"
thiserror = "1.0"
tokio = { version = "1.32", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = "0.3"
uniffi = "0.25"
url-fork = { version = "3.0", default-features = false }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"