[workspace]
members = [
    "bindings/nostr-ffi",
    "bindings/nostr-js",
    "bindings/nostr-sdk-ffi",
    "bindings/nostr-sdk-js",
    "bindings/uniffi-bindgen",
    "crates/*",
    "crates/nostr-database/fuzz/perf"
]
default-members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>", "Rust Nostr Developers"]
homepage = "https://github.com/rust-nostr/nostr"
repository = "https://github.com/rust-nostr/nostr.git"
license = "MIT"

[workspace.dependencies]
async-trait = "0.1"
js-sys = "0.3"
nostr = { version = "0.25", path = "./crates/nostr", default-features = false }
nostr-database = { version = "0.1", path = "./crates/nostr-database", default-features = false }
once_cell = "1.18"
thiserror = "1.0"
tokio = { version = "1", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = "0.3"
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "59c1e3ef15b1ea5143402e25264e933dbf8d1a1f" }
url-fork = { version = "3.0", default-features = false }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"