[package]
name = "nostr-ffi"
version = "0.1.0"
edition = "2021"
authors.workspace = true
publish = false

[lib]
name = "nostr_ffi"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
nostr  = { path = "../../crates/nostr", features = ["blocking"] }
uniffi = { workspace = true }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
