[package]
name = "nostr-ffi"
version = "0.1.0"
edition = "2021"
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
keywords = ["nostr", "ffi"]

[lib]
name = "nostr_ffi"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
nostr  = { path = "../../crates/nostr", features = ["blocking", "vanity"] }
uniffi = { workspace = true }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
