[package]
name = "nostr-cli"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
clap = { version = "4.3", features = ["derive"] }
dialoguer = "0.11"
nostr-sdk = { version = "0.29", path = "../nostr-sdk", features = ["sqlite"] }
once_cell.workspace = true
prettytable-rs = "0.10"
rayon = "1.9"
regex = "=1.9.6" # PIN for MSRV 1.64.0
rustyline = { version = "12.0", default-features = false }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["full"] }
tracing-subscriber.workspace = true
