[package]
name = "nostr-cli"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dialoguer = "0.11"
dirs = "5.0"
nostr-relay-builder.workspace = true
nostr-sdk = { workspace = true, features = ["all-nips", "lmdb"] }
once_cell.workspace = true
prettytable-rs = "0.10"
regex = "1.9.6"
rustyline = { version = "14.0", default-features = false, features = ["with-file-history"] }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["full"] }
