name: nostr_sdk_snippets_flutter
description: "A sample command-line application."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  nostr_sdk:
    git:
      url: https://github.com/rust-nostr/nostr-sdk-flutter.git
      ref: 2e63f8f6cfac533061b8f8f776898aca3291d95a

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
