name: nostr_sdk_snippets_flutter
description: "A sample command-line application."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  nostr_sdk:
    git:
      url: https://github.com/rust-nostr/nostr-sdk-flutter.git
      ref: 1b1af0cdd0cf221e2706430f05242757a9574604

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
