[package]
name = "nostr-sdk"
version = "0.25.0"
edition = "2021"
description = "High level Nostr client library."
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version = "1.64.0"
keywords = ["nostr", "sdk"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["all-nips"]
blocking = ["async-utility/blocking", "nostr/blocking"]
rocksdb = ["dep:nostr-rocksdb"]
indexeddb = ["dep:nostr-indexeddb"]
all-nips = ["nip04", "nip05", "nip06", "nip11", "nip46", "nip47"]
nip03 = ["nostr/nip03"]
nip04 = ["nostr/nip04"]
nip05 = ["nostr/nip05"]
nip06 = ["nostr/nip06"]
nip11 = ["nostr/nip11"]
nip44 = ["nostr/nip44"]
nip46 = ["nostr/nip46"]
nip47 = ["nostr/nip47"]

[dependencies]
async-utility = "0.1"
nostr = { workspace = true, features = ["std"] }
nostr-database = { workspace = true }
nostr-sdk-net = { version = "0.25", path = "../nostr-sdk-net" }
once_cell = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, features = ["std"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nostr-rocksdb = { version = "0.1", path = "../nostr-rocksdb", optional = true }
tokio = { workspace = true, features = ["rt-multi-thread", "time", "macros", "sync"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
nostr-indexeddb = { version = "0.1", path = "../nostr-indexeddb", optional = true }
tokio = { workspace = true, features = ["rt", "macros", "sync"] }

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[[example]]
name = "client-with-opts"
required-features = ["all-nips"]

[[example]]
name = "client"
required-features = ["all-nips"]

[[example]]
name = "get-events-of"
required-features = ["all-nips"]

[[example]]
name = "blocking"
required-features = ["all-nips", "blocking"]

[[example]]
name = "nostr-connect"
required-features = ["nip46"]

[[example]]
name = "bot"
required-features = ["all-nips"]

[[example]]
name = "client-stop"
required-features = ["all-nips"]

[[example]]
name = "rocksdb"
required-features = ["all-nips", "rocksdb"]

[[example]]
name = "shutdown-on-drop"

[[example]]
name = "subscriptions"
required-features = ["all-nips"]

[[example]]
name = "negentropy"

[[example]]
name = "nip65"