[package]
name = "nostr-sdk-js"
version = "0.1.0"
edition = "2021"
authors.workspace = true
publish = false

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
async-utility.workspace = true
js-sys.workspace = true
nostr-js = { path = "../nostr-js" }
nostr-sdk = { path = "../../crates/nostr-sdk", default-features = false, features = ["all-nips", "indexeddb"] }
tracing.workspace = true
tracing-subscriber.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = true
