[package]
name = "nostr-sdk-js"
version = "0.1.0"
edition = "2021"
authors.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3"
nostr-js = { path = "../nostr-js" }
nostr-sdk = { path = "../../crates/nostr-sdk" }
serde-wasm-bindgen = "0.5"
tracing-wasm = "0.2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = true
