[package]
name = "nostr-sdk-signer"
version = "0.27.0"
edition = "2021"
description = "Nostr SDK Signer"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "sdk", "signer"]

[features]
default = ["nip04", "nip07", "nip44", "nip46"]
nip04 = ["nostr/nip04"]
nip07 = ["nostr/nip07"]
nip44 = ["nostr/nip44"]
nip46 = ["nostr/nip46", "dep:nostr-sdk-pool"]

[dependencies]
async-utility.workspace = true
nostr = { workspace = true, features = ["std"] }
nostr-sdk-pool = { workspace = true, optional = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
