[package]
name = "nostr-sdk-flutter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0"
flutter_rust_bridge = "=2.5.1"
nostr-sdk  = { workspace = true, default-features = false, features = ["all-nips"] }
