[package]
name = "nostr-sdk-ffi"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "nostr_sdk_ffi"
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = ["lmdb", "sqlite", "ndb"]
lmdb = ["nostr-sdk/lmdb"]
sqlite = ["nostr-sdk/sqlite"]
ndb = ["nostr-sdk/ndb"]

[dependencies]
async-trait.workspace = true
async-utility.workspace = true
nostr-ffi  = { path = "../nostr-ffi" }
nostr-relay-builder.workspace = true
nostr-sdk  = { workspace = true, default-features = false, features = ["all-nips", "tor"] }
tracing = { workspace = true, features = ["std"] }
tracing-subscriber.workspace = true
uniffi = { workspace = true, features = ["tokio"] }

[target.'cfg(target_os = "android")'.dependencies]
paranoid-android = "0.2"
