[package]
name = "nostr-sdk-ffi"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "nostr_sdk_ffi"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[features]
default = ["lmdb"]
lmdb = ["nostr-sdk/lmdb"]
ndb = ["nostr-sdk/ndb"]

[dependencies]
async-trait.workspace = true
nostr = { workspace = true, features = ["std", "all-nips"] }
nostr-connect.workspace = true
nostr-relay-builder.workspace = true
nostr-sdk  = { workspace = true, default-features = false, features = ["all-nips", "tor"] }
tracing = { workspace = true, features = ["std"] }
tracing-subscriber.workspace = true
uniffi = { version = "=0.28.0", features = ["cli", "tokio"] } # cli feature is required for the `uniffi-bindgen` binary

[target.'cfg(target_os = "android")'.dependencies]
paranoid-android = "0.2"

[dev-dependencies]
uniffi = { version = "=0.28.0", features = ["bindgen-tests"] }
