[package]
name = "nostr-sdk-ffi"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "nostr_sdk_ffi"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
async-utility.workspace = true
nostr-ffi  = { path = "../nostr-ffi" }
nostr-sdk  = { path = "../../crates/nostr-sdk", default-features = false, features = ["all-nips", "blocking", "sqlite"] }
tracing = { workspace = true, features = ["std"] }
tracing-subscriber.workspace = true
uniffi.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
paranoid-android = "0.2"