[package]
name = "nostr-webln"
version = "0.34.0"
edition = "2021"
description = "WebLN zapper backend for Nostr apps"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "zapper", "webln"]

[dependencies]
nostr-zapper.workspace = true
webln = "0.2"