[package]
name = "nostr-database-perf"
version = "0.1.0"
edition = "2021"

[dependencies]
nostr-database = { path = "../../" }
serde_json = "1.0"
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
