[tool.poetry]
name = "book"
version = "0.1.0"
description = "Rust Nostr Book"
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<4"
mkdocs-material = "9.4"
