[package]
authors.workspace = true
edition = "2021"
homepage.workspace = true
license.workspace = true
name = "rust"
repository.workspace = true
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr-sdk = "0.26"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
