[package]
name = "snippets-nostr-sdk-rust"
version = "0.1.0"
edition = "2021"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[dependencies]
nostr-sdk = "0.32"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }