name: Deploy Book

on:
  push:
    paths:
      - 'book/**'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  deploy:
    name: Deploy book
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init
        run: cd book && make init

      - name: Build
        run: cd book && make build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book